server:
    port: 8080
    session.timeout: 1800 # Seconds

spring:
    profiles:
        active: local-dev
    datasource:
        dataSourceClassName: org.h2.jdbcx.JdbcDataSource
        url: jdbc:h2:mem:jhipster;DB_CLOSE_DELAY=-1
        databaseName:
        serverName:
        username:
        password:

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
    mail:
        host: localhost
        port: 2525

feedback:
    efecte.address: opetusteknologia@helsinki.fi

metrics:
    jmx.enabled: false

oodi:
    base.url: https://esbmt2.it.helsinki.fi:4443/doo-oodi/dev/testdb
    client.implementation: mock

coursePage:
    base.url: https://dev.student.helsinki.fi/api/v1
    client.implementation: mock
    defaultCourseImageUri: /assets/images/course/default_course_image.jpg

esb:
    base.url: https://esbmt2.it.helsinki.fi/devel
    client.implementation: mock

unisport:
    client.implementation: mock
    base.url: https://unisport.fi
    userAuthorizationUrl: http://yol-test.it.helsinki.fi/ext/opintoni/authorization

unisportApiKey: foobar123

leiki:
    base.url: http://suositukset.student.helsinki.fi
    client.implementation: mock

googleAnalyticsAccount:
    main: UA-55852460-3
    student: UA-55852460-9
    teacher: UA-55852460-9

hostUrl: http://local.student.helsinki.fi:3000
loginUrlTeacher: http://local.teacher.helsinki.fi:3000/info/local-login
loginUrlStudent: http://local.student.helsinki.fi:3000/info/local-login
logoutUrl: /logout
teacherAppUrl: http://local.teacher.helsinki.fi:3000
studentAppUrl: http://local.student.helsinki.fi:3000
portfolioUrl:
  student: http://local.student.helsinki.fi:3002/portfolio
  teacher: http://local.teacher.helsinki.fi:3002/portfolio

mece:
  domain: https://ohtu-testi.it.helsinki.fi

environment: local

adminAccounts: opettaja@helsinki.fi, opiskelija@helsinki.fi

feed.client.implementation: mock

meceSecretKey: W778UXMJ7PFQTKG2RM8NR2H7T3QE5ZTL

embedlyApiKey: dd741e653b0e4841bc59a60650031057
