server:
    port: 8080
    session:
        timeout: 1800 # Seconds
        cookie:
            http-only: true
            path: /
            domain: helsinki.fi

# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

feedback:
    recipient:
        student: neu-tuki@helsinki.fi
        teacher: opetusteknologia@helsinki.fi

    anonymous:
        fromAddress: doo-projekti@helsinki.fi
        replyToAddress: noreply@helsinki.fi

hibernate:
    connection:
        handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION

userDefaults :
    defaultFavorites:
        - type: UNICAFE
          restaurantId : 39
        - type: TWITTER
          value: helsinkiuni
        - type: RSS
          url: https://www.helsinki.fi/fi/feeds/news/rss
        - type: RSS
          url: http://helsinginyliopisto.etapahtuma.fi/Default.aspx?tabid=959&format=atom
    defaultUsefulLinks :
        studentDefaultUsefulLinks :
            - url: http://helsinki.fi/office365
              description: usefulLinks.email
              orderIndex: 0
            - url: https://helsinkifi-my.sharepoint.com/
              description: usefulLinks.oneDrive
              orderIndex: 1
        teacherDefaultUsefulLinks :
            - url: https://flamma.helsinki.fi/portal/home/sisalto?_nfpb=true&_pageLabel=pp_list&placeId=HY1001598
              description: usefulLinks.academicAdministration
              orderIndex: 0
            - url: https://flamma.helsinki.fi/portal/home/sisalto?_nfpb=true&_pageLabel=pp_list&placeId=HY1001593
              description: usefulLinks.professionalDevelopment
              orderIndex: 6
            - url:
                fi: https://flamma.helsinki.fi/fi/HY053909
                sv: https://flamma.helsinki.fi/sv/HY053909
                en: https://flamma.helsinki.fi/en/HY053909
              description: usefulLinks.planningSupport
              orderIndex: 7
            - url: http://tuhat.helsinki.fi/
              description: usefulLinks.tuhat
              orderIndex: 8
            - url: https://www.researchgate.net/
              description: usefulLinks.researchGate
              orderIndex: 9
            - url: http://www.helsinki.fi/optime
              description: usefulLinks.optimePortal
              orderIndex: 10
            - url: https://helsinkifi-my.sharepoint.com/
              description: usefulLinks.oneDrive
              orderIndex: 11
        studentOpenUniversityDefaultUsefulLinks:
            - url:
                fi: https://www.helsinki.fi/fi/avoin-yliopisto
                sv: https://www.helsinki.fi/sv/oppna-universitetet
                en: https://www.helsinki.fi/en/open-university
              description: usefulLinks.openUniversity
              orderIndex: 0
            - url: https://www.avoin.helsinki.fi/omat/osallistumiset/
              description: usefulLinks.openUniversityMyPages
              orderIndex: 1
        teacherOpenUniversityDefaultUsefulLinks:
            - url: https://flamma.helsinki.fi/fi/HY311604
              description: usefulLinks.teachingSupportOpenUniversity
              orderIndex: 2
            - url: https://flamma.helsinki.fi/fi/HY311747
              description: usefulLinks.teachingPracticesInOpenUniversity
              orderIndex: 3
            - url: http://www.helsinki.fi/optime
              description: usefulLinks.optimePortal
              orderIndex: 4
    defaultFacultyCode: default
    facultyUsefulLinks:
        teacherFacultyLinks:
            - faculty: A57000
              url: https://flamma.helsinki.fi/fi/HY301045
              description: usefulLinks.teachingSupport
              orderIndex: 1
            - faculty: A90000
              url: https://flamma.helsinki.fi/fi/HY306071
              description: usefulLinks.forTeacher
              orderIndex: 1
            - faculty: A55000
              url: https://flamma.helsinki.fi/fi/HY300953
              description: usefulLinks.forPersonnel
              orderIndex: 1
            - faculty: A40000
              url: https://flamma.helsinki.fi/fi/HY291485
              description: usefulLinks.teachingSupport
              orderIndex: 1
            - faculty: A60000
              url: https://flamma.helsinki.fi/fi/HY302860
              description: usefulLinks.forPersonnel
              orderIndex: 1
            - faculty: A30000
              url: https://flamma.helsinki.fi/fi/HY291609
              description: usefulLinks.teaching
              orderIndex: 1
            - faculty: A80000
              url: https://flamma.helsinki.fi/fi/HY301055
              description: usefulLinks.forPersonnel
              orderIndex: 1
            - faculty: A50000
              url: https://flamma.helsinki.fi/fi/HY287029
              description: usefulLinks.forPersonnel
              orderIndex: 1
            - faculty: A20000
              url: https://flamma.helsinki.fi/fi/HY307740
              description: usefulLinks.teachingSupport
              orderIndex: 1
            - faculty: A74000
              url: https://flamma.helsinki.fi/sv/HY286442
              description: usefulLinks.teachingMatters
              orderIndex: 1
            - faculty: A10000
              url: https://flamma.helsinki.fi/fi/HY292308
              description: usefulLinks.teachingSupport
              orderIndex: 1
            - faculty: A70000
              url: https://flamma.helsinki.fi/fi/HY286934
              description: usefulLinks.teachingMatters
              orderIndex: 1
            - faculty: default
              url: https://flamma.helsinki.fi/fi/default
              description: usefulLinks.teachingMatters
              orderIndex: 1
            - faculty: A93000
              url: https://www.avoin.helsinki.fi/omat/osallistumiset/
              description: usefulLinks.openUniversity
              orderIndex: 1

courses:
    examTypeCodes: 8,16,19,20,23,27,28

avatarSize: 510
saml:
  idp.metadataUrl: https://login.helsinki.fi/metadata/sign-hy-metadata.xml
  teacher:
    alias: teacher
  student:
    alias: student

studentAppUrl:
teacherAppUrl:
appRelativeUrl:

leiki:
    base.url: http://suositukset.student.helsinki.fi
    client.implementation: rest

newsfeeds:
    studentFeedsByLocale:
        fi: https://flamma.helsinki.fi/infotaulu/atom-news.xml
        sv: https://flamma.helsinki.fi/infotaulu/atom-news-sv.xml
        en: https://flamma.helsinki.fi/infotaulu/atom-news-en.xml
    teacherFeedsByLocale:
        fi: https://flamma.helsinki.fi/infotaulu/atom-tiedotteet-opetusasiat.xml
        sv: https://flamma.helsinki.fi/infotaulu/atom-tiedotteet-opetusasiat-sv.xml
        en: https://flamma.helsinki.fi/infotaulu/atom-tiedotteet-opetusasiat-en.xml

publicWww:
    base.url: https://www.helsinki.fi
    path: fi/feeds/filtered-news/rss/11405/all

unisport:
    tokenValidForSeconds: 10
    jwt.service.implementation: expiring

search:
  maxSearchResults: 100
  maxCategoryResults: 10

recommendations:
  maxRecommendations: 20
  uidPrefix: opintohistoriatesti_

httpClient:
  readTimeout: 15000
  connectTimeout: 3000
  maxTotal: 500
  defaultMaxPerRoute: 500

cache:
    timeToLiveSeconds: 3600
    studentEvents:
        timeToLiveSeconds: 3600
        maxEntriesLocalHeap: 600
    studentEnrollments:
        timeToLiveSeconds: 1800
        maxEntriesLocalHeap: 500
    teacherEvents:
        timeToLiveSeconds: 3600
        maxEntriesLocalHeap: 500
    teacherCourses:
        timeToLiveSeconds: 3600
        maxEntriesLocalHeap: 500
    coursePage:
        timeToLiveSeconds: 86400
        maxEntriesLocalHeap: 10000
    courseUniRealisations:
        timeToLiveSeconds: 28800
        maxEntriesLocalHeap: 10000
    studentNews:
        timeToLiveSeconds: 3600
        maxEntriesLocalHeap: 1
    teacherNews:
        timeToLiveSeconds: 3600
        maxEntriesLocalHeap: 1
    isOpenUniversityStudent:
        timeToLiveSeconds: 86400
        maxEntriesLocalHeap: 10000
    isOpenUniversityTeacher:
        timeToLiveSeconds: 86400
        maxEntriesLocalHeap: 5000
    europeHelsinkiTimeZone:
        timeToLiveSeconds: 3600
        maxEntriesLocalHeap: 1
    feeds:
        timeToLiveSeconds: 3600
        maxEntriesLocalHeap: 200

staticResourceCachingPeriod: 31536000

fileStorage:
  path: /opt/opintoni/files
  uri: /files

facultyLinks:
  A93000: https://flamma.helsinki.fi/portal/units/avoin
  H57: https://flamma.helsinki.fi/portal/units/bio
  H90: https://flamma.helsinki.fi/portal/units/vetmed
  H55: https://flamma.helsinki.fi/portal/units/farmasia
  H40: https://flamma.helsinki.fi/portal/units/hum
  H60: https://flamma.helsinki.fi/portal/units/kaytt
  H30: https://flamma.helsinki.fi/portal/units/ltdk
  H80: https://flamma.helsinki.fi/portal/units/mmtdk
  H50: https://flamma.helsinki.fi/portal/units/matlu
  H20: https://flamma.helsinki.fi/portal/units/law
  H74: https://flamma.helsinki.fi/portal/units/sockom
  H10: https://flamma.helsinki.fi/portal/units/teologinen
  H70: https://flamma.helsinki.fi/portal/units/valt
  A57000: https://flamma.helsinki.fi/portal/units/bio
  A90000: https://flamma.helsinki.fi/portal/units/vetmed
  A55000: https://flamma.helsinki.fi/portal/units/farmasia
  A40000: https://flamma.helsinki.fi/portal/units/hum
  A60000: https://flamma.helsinki.fi/portal/units/kaytt
  A30000: https://flamma.helsinki.fi/portal/units/ltdk
  A80000: https://flamma.helsinki.fi/portal/units/mmtdk
  A50000: https://flamma.helsinki.fi/portal/units/matlu
  A20000: https://flamma.helsinki.fi/portal/units/law
  A74000: https://flamma.helsinki.fi/portal/units/sockom
  A10000: https://flamma.helsinki.fi/portal/units/teologinen
  A70000: https://flamma.helsinki.fi/portal/units/valt

feed.client.implementation: remote

locale.default: fi

pilotDegreeProgrammes:
    - KH40_001
    - KH50_002
    - KH50_006
    - KH40_006
    - KH50_003
    - KH40_003
    - KH40_004
    - KH40_005
    - KH50_007
    - KH50_004
    - KH50_001
    - KH40_002
    - KH10_001
    - KH50_005
    - MH50_004
    - MH40_012
    - MH50_010
    - MH40_005
    - MH50_002
    - MH40_003
    - MH50_011
    - MH40_015
    - MH50_006
    - MH50_013
    - MH50_007
    - MH40_002
    - MH40_009
    - MH40_013
    - MH40_010
    - MH40_006
    - MH50_012
    - MH50_001
    - MH50_008
    - MH50_005
    - MH40_008
    - MH40_014
    - MH40_007
    - MH40_001
    - MH10_001
    - MH50_003
    - MH50_009

