# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

spring:
    messageSource:
        cacheSeconds: 1

userDefaults :
    defaultFavorites:
        - type: UNICAFE
          restaurantId : 3
        - type: TWITTER
          value: helsinkiuni
        - type: RSS
          url: http://helsinginyliopisto.etapahtuma.fi/Default.aspx?tabid=959&format=atom
          visibleItems: 3
        - type: RSS
          url: https://university.helsinki.fi/fi/feeds/news/rss
          visibleItems: 3
        - type: RSS
          url: http://hyy.helsinki.fi/en/feed/uutiset/rss.xml
          visibleItems: 3
        - type: TWITTER
          value: opinder_uh
        - type: RSS
          url: http://www.helsinki.fi/blogit/feed/postfeed.php
          visibleItems: 3
        - type: RSS
          url: http://yle.fi/uutiset/rss/uutiset.rss?osasto=tiede
          visibleItems: 3
    defaultUsefulLinks :
        studentDefaultUsefulLinks :
            - url:
                fi: https://flamma.helsinki.fi/fi/HY034202
                sv: https://flamma.helsinki.fi/sv/HY034202
                en: https://flamma.helsinki.fi/en/HY034202
              description: usefulLinks.studentServices
              orderIndex: 0
            - url:
                fi: https://flamma.helsinki.fi/fi/HY034217
                sv: https://flamma.helsinki.fi/sv/HY034217
                en: https://flamma.helsinki.fi/en/HY034217
              description: usefulLinks.healthAndWellbeing
              orderIndex: 5
            - url: https://flamma.helsinki.fi/portal/home/sisalto?_nfpb=true&_pageLabel=pp_list&placeId=HY034234
              description: usefulLinks.studyingAndTrainingAbroad
              orderIndex: 6
            - url:
                fi: http://www.aarresaari.net/index.php?13&uniid=7&lang_id=2
                sv: http://www.aarresaari.net/index.php?39&uniid=7&lang_id=4
                en: http://www.aarresaari.net/index.php?32&uniid=7&lang_id=1
              description: usefulLinks.rekryNet
              orderIndex: 7
            - url: https://helsinkifi-my.sharepoint.com/
              description: usefulLinks.oneDrive
              orderIndex: 8
        teacherDefaultUsefulLinks :
            - url: https://flamma.helsinki.fi/portal/home/sisalto?_nfpb=true&_pageLabel=pp_list&placeId=HY1001598
              description: usefulLinks.academicAdministration
              orderIndex: 0
            - url: https://flamma.helsinki.fi/portal/home/sisalto?_nfpb=true&_pageLabel=pp_list&placeId=HY1001593
              description: usefulLinks.professionalDevelopment
              orderIndex: 6
            - url:
                fi: https://flamma.helsinki.fi/fi/HY053909
                sv: https://flamma.helsinki.fi/sv/HY053909
                en: https://flamma.helsinki.fi/en/HY053909
              description: usefulLinks.planningSupport
              orderIndex: 7
            - url: http://tuhat.helsinki.fi/
              description: usefulLinks.tuhat
              orderIndex: 8
            - url: https://www.researchgate.net/
              description: usefulLinks.researchGate
              orderIndex: 9
            - url: https://helsinkifi-my.sharepoint.com/
              description: usefulLinks.oneDrive
              orderIndex: 11
        studentOpenUniversityDefaultUsefulLinks:
            - url:
                fi: https://www.helsinki.fi/fi/avoin-yliopisto
                sv: https://www.helsinki.fi/sv/oppna-universitetet
                en: https://www.helsinki.fi/en/open-university
              description: usefulLinks.openUniversity
              orderIndex: 3
            - url: https://www.avoin.helsinki.fi/omat/osallistumiset/
              description: usefulLinks.openUniversityMyPages
              orderIndex: 4
        teacherOpenUniversityDefaultUsefulLinks:
            - url: https://flamma.helsinki.fi/fi/HY311604
              description: usefulLinks.teachingSupportOpenUniversity
              orderIndex: 2
            - url: https://flamma.helsinki.fi/fi/HY311747
              description: usefulLinks.teachingPracticesInOpenUniversity
              orderIndex: 3
    facultyUsefulLinks :
        defaultFacultyCode: default
        teacherFacultyLinks:
            - faculty: A57000
              url: https://flamma.helsinki.fi/fi/HY301045
              description: usefulLinks.teachingSupport
              orderIndex: 1
            - faculty: A90000
              url: https://flamma.helsinki.fi/fi/HY306071
              description: usefulLinks.forTeacher
              orderIndex: 1
            - faculty: A55000
              url: https://flamma.helsinki.fi/fi/HY300953
              description: usefulLinks.forPersonnel
              orderIndex: 1
            - faculty: A40000
              url: https://flamma.helsinki.fi/fi/HY291485
              description: usefulLinks.teachingSupport
              orderIndex: 1
            - faculty: A60000
              url: https://flamma.helsinki.fi/fi/HY302860
              description: usefulLinks.forPersonnel
              orderIndex: 1
            - faculty: A30000
              url: https://flamma.helsinki.fi/fi/HY291609
              description: usefulLinks.teaching
              orderIndex: 1
            - faculty: A80000
              url: https://flamma.helsinki.fi/fi/HY301055
              description: usefulLinks.forPersonnel
              orderIndex: 1
            - faculty: A50000
              url: https://flamma.helsinki.fi/fi/HY287029
              description: usefulLinks.forPersonnel
              orderIndex: 1
            - faculty: A20000
              url: https://flamma.helsinki.fi/fi/HY307740
              description: usefulLinks.teachingSupport
              orderIndex: 1
            - faculty: A74000
              url: https://flamma.helsinki.fi/sv/HY286442
              description: usefulLinks.teachingMatters
              orderIndex: 1
            - faculty: A10000
              url: https://flamma.helsinki.fi/fi/HY292308
              description: usefulLinks.teachingSupport
              orderIndex: 1
            - faculty: A70000
              url: https://flamma.helsinki.fi/fi/HY286934
              description: usefulLinks.teachingMatters
              orderIndex: 1
            - faculty: default
              url: https://flamma.helsinki.fi/portal/home/sisalto?_nfpb=true&_pageLabel=pp_list&placeId=HY034203
              description: usefulLinks.teachingMatters
              orderIndex: 1
            - faculty: A93000
              url: https://www.avoin.helsinki.fi/omat/osallistumiset/
              description: usefulLinks.openUniversity
              orderIndex: 1
            - faculty: A57000
              url: http://www.helsinki.fi/optime
              description: usefulLinks.optimePortal
              orderIndex: 10
            - faculty: A90000
              url: http://www.helsinki.fi/optime
              description: usefulLinks.optimePortal
              orderIndex: 10
            - faculty: A55000
              url: http://www.helsinki.fi/optime
              description: usefulLinks.optimePortal
              orderIndex: 10
            - faculty: A60000
              url: http://www.helsinki.fi/optime
              description: usefulLinks.optimePortal
              orderIndex: 10
            - faculty: A80000
              url: http://www.helsinki.fi/optime
              description: usefulLinks.optimePortal
              orderIndex: 10
            - faculty: A50000
              url: http://www.helsinki.fi/optime
              description: usefulLinks.optimePortal
              orderIndex: 10
        studentFacultyLinks:
            - faculty: H57
              url: https://flamma.helsinki.fi/fi/HY300842
              description: usefulLinks.forStudent
              orderIndex: 1
            - faculty: H90
              url: https://flamma.helsinki.fi/fi/HY297557
              description: usefulLinks.forStudent
              orderIndex: 1
            - faculty: H55
              url: https://flamma.helsinki.fi/fi/HY300952
              description: usefulLinks.forStudent
              orderIndex: 1
            - faculty: H40
              url: https://flamma.helsinki.fi/fi/HY290050
              description: usefulLinks.forStudent
              orderIndex: 1
            - faculty: H60
              url: https://flamma.helsinki.fi/fi/HY303821
              description: usefulLinks.forStudent
              orderIndex: 1
            - faculty: H30
              url: https://flamma.helsinki.fi/fi/HY291608
              description: usefulLinks.forStudent
              orderIndex: 1
            - faculty: H80
              url: https://flamma.helsinki.fi/fi/HY301046
              description: usefulLinks.forStudent
              orderIndex: 1
            - faculty: H50
              url: https://flamma.helsinki.fi/fi/HY287012
              description: usefulLinks.forStudent
              orderIndex: 1
            - faculty: H20
              url: https://flamma.helsinki.fi/fi/HY307150
              description: usefulLinks.forStudent
              orderIndex: 1
            - faculty: H74
              url: https://flamma.helsinki.fi/sv/HY284948
              description: usefulLinks.forStudent
              orderIndex: 1
            - faculty: H10
              url: https://flamma.helsinki.fi/fi/HY292307
              description: usefulLinks.forStudent
              orderIndex: 1
            - faculty: H70
              url: https://flamma.helsinki.fi/fi/HY286484
              description: usefulLinks.forStudent
              orderIndex: 1
            - faculty: H70
              url: https://opinder.helsinki.fi
              description: usefulLinks.opinder
              orderIndex: 2
            - faculty: A30000
              url:
                fi: https://flamma.helsinki.fi/fi/HY291608
                sv: https://flamma.helsinki.fi/sv/HY300404
                en: https://flamma.helsinki.fi/en/HY317377
              description: usefulLinks.forStudent
              orderIndex: 1
            - faculty: A30000
              url:
                fi: https://weboodi.helsinki.fi/hy/opasopiskopas.jsp?MD5avain=&Kieli=1&Organisaatio=1000000836&AukOrg=1000000836#1000000836
                sv: https://weboodi.helsinki.fi/hy/opasopiskopas.jsp?MD5avain=&Kieli=2&Organisaatio=1000000836&AukOrg=1000000836#1000000836
                en: https://weboodi.helsinki.fi/hy/opasopiskopas.jsp?MD5avain=&Kieli=6&Organisaatio=1000000836&AukOrg=1000000836#1000000836
              description: usefulLinks.courseCatalogs
              orderIndex: 2

courses:
    examTypeCodes: 8,16,19,20,23,27

avatarSize: 510
saml:
  idp.metadataUrl: https://login.helsinki.fi/metadata/sign-hy-metadata.xml
  teacher:
    alias: teacher
  student:
    alias: student

studentAppUrl:
teacherAppUrl:
appRelativeUrl:

leiki:
    base.url: http://suositukset.student.helsinki.fi
    client.implementation: rest

flamma:
    base.url: https://flamma.helsinki.fi

unisport:
    userAuthorizationUrl: https://unisport.fi/ext/opintoni/authorization
    tokenValidForSeconds: 10
    jwt.service.implementation: expiring

search:
  maxSearchResults: 100
  maxCategoryResults: 10

recommendations:
  maxRecommendations: 5
  uidPrefix: opintohistoriatesti_

cookieDomain: helsinki.fi

httpClient:
  readTimeout: 15000
  connectTimeout: 3000
  maxTotal: 500
  defaultMaxPerRoute: 500

cache:
    timeToLiveSeconds: 3600
    studentEvents:
        timeToLiveSeconds: 3600
        maxEntriesLocalHeap: 500
    studentEnrollments:
        timeToLiveSeconds: 1800
        maxEntriesLocalHeap: 500
    teacherEvents:
        timeToLiveSeconds: 3600
        maxEntriesLocalHeap: 500
    teacherCourses:
        timeToLiveSeconds: 3600
        maxEntriesLocalHeap: 500
    coursePage:
        timeToLiveSeconds: 7200
        maxEntriesLocalHeap: 7000
    coursePageOneOffEvents:
        timeToLiveSeconds: 7200
        maxEntriesLocalHeap: 5000
    courseUniRealisations:
        timeToLiveSeconds: 28800
        maxEntriesLocalHeap: 5000
    studentNews:
        timeToLiveSeconds: 3600
        maxEntriesLocalHeap: 1
    teacherNews:
        timeToLiveSeconds: 3600
        maxEntriesLocalHeap: 1
    isOpenUniversityStudent:
        timeToLiveSeconds: 86400
        maxEntriesLocalHeap: 10000
    isOpenUniversityTeacher:
        timeToLiveSeconds: 86400
        maxEntriesLocalHeap: 5000
    europeHelsinkiTimeZone:
        timeToLiveSeconds: 3600
        maxEntriesLocalHeap: 1
    feeds:
        timeToLiveSeconds: 3600
        maxEntriesLocalHeap: 200

staticResourceCachingPeriod: 31536000

fileStorage:
  path: /opt/opintoni/files
  uri: /files

facultyLinks:
  A93000: https://flamma.helsinki.fi/portal/units/avoin
  H57: https://flamma.helsinki.fi/portal/units/bio
  H90: https://flamma.helsinki.fi/portal/units/vetmed
  H55: https://flamma.helsinki.fi/portal/units/farmasia
  H40: https://flamma.helsinki.fi/portal/units/hum
  H60: https://flamma.helsinki.fi/portal/units/kaytt
  H30: https://flamma.helsinki.fi/portal/units/ltdk
  H80: https://flamma.helsinki.fi/portal/units/mmtdk
  H50: https://flamma.helsinki.fi/portal/units/matlu
  H20: https://flamma.helsinki.fi/portal/units/law
  H74: https://flamma.helsinki.fi/portal/units/sockom
  H10: https://flamma.helsinki.fi/portal/units/teologinen
  H70: https://flamma.helsinki.fi/portal/units/valt
  A57000: https://flamma.helsinki.fi/portal/units/bio
  A90000: https://flamma.helsinki.fi/portal/units/vetmed
  A55000: https://flamma.helsinki.fi/portal/units/farmasia
  A40000: https://flamma.helsinki.fi/portal/units/hum
  A60000: https://flamma.helsinki.fi/portal/units/kaytt
  A30000: https://flamma.helsinki.fi/portal/units/ltdk
  A80000: https://flamma.helsinki.fi/portal/units/mmtdk
  A50000: https://flamma.helsinki.fi/portal/units/matlu
  A20000: https://flamma.helsinki.fi/portal/units/law
  A74000: https://flamma.helsinki.fi/portal/units/sockom
  A10000: https://flamma.helsinki.fi/portal/units/teologinen
  A70000: https://flamma.helsinki.fi/portal/units/valt

feed.client.implementation: remote

locale.default: fi
