server:
    session:
        cookie:
            name: OO_DEV_SESSION_ID
            secure: true

spring:
    profiles:
        active: dev
    datasource:
        dataSourceClassName: ${datasource.dataSourceClassName}
        url: ${datasource.url}
        databaseName: ${datasource.databaseName}
        serverName: ${datasource.serverName}
        username: ${datasource.username}
        password: ${datasource.password}

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        database: ${jpa.database}
        openInView: ${jpa.openInView}
        show_sql: ${jpa.show_sql}
        generate-ddl: ${jpa.generate-ddl}
        hibernate:
            ddl-auto: ${jpa.hibernate.ddl-auto}
            naming-strategy: ${jpa.hibernate.naming-strategy}
        properties:
            hibernate.cache.use_second_level_cache: ${jpa.properties.hibernate.cache.use_second_level_cache}
            hibernate.cache.use_query_cache: ${jpa.properties.hibernate.cache.use_query_cache}
            hibernate.generate_statistics: ${jpa.properties.hibernate.generate_statistics}
            hibernate.cache.region.factory_class: ${jpa.properties.hibernate.cache.region.factory_class}
    mail:
        host: smtp.helsinki.fi
        port: 25

feedback:
    recipient:
        student: studentfeedback@localhost
        teacher: teacherfeedback@localhost
        portfolio: portfoliofeedback@localhost
        academicPortfolio: academicportfoliofeedback@localhost

metrics:
    jmx.enabled: true

oodi:
    base.url: https://esbmt2.it.helsinki.fi:443/doo-oodi/dev/testdb
    client.implementation: mock
    useHttpClientCertificate: false

coursePage:
    base.url: https://dev.courses.helsinki.fi
    api.path: /api/v1
    client.implementation: mock
    defaultCourseImageUri: /assets/images/course/default_course_image.jpg

guide:
    base.url: https://dev.guide.student.helsinki.fi/api/v1
    client.implementation: mock

esb:
    base.url: https://esbmt2.it.helsinki.fi/devel
    client.implementation: mock

unisport:
    client.implementation: mock
    base.url: https://unisport.fi
    userAuthorizationUrl: http://yol-test.it.helsinki.fi/ext/opintoni/authorization

unisportApiKey: foobar123

googleAnalyticsAccount:
    main: UA-55852460-3
    student: UA-55852460-9
    teacher: UA-55852460-9

hostUrl: https://dev.student.helsinki.fi
loginUrlTeacher: https://dev.teacher.helsinki.fi/info/local-login
loginUrlStudent: https://dev.student.helsinki.fi/info/local-login
logoutUrl: /logout
teacherAppUrl: https://dev.teacher.helsinki.fi
studentAppUrl: https://dev.student.helsinki.fi
portfolioUrl:
  student: https://dev.student.helsinki.fi/portfolio
  teacher: https://dev.teacher.helsinki.fi/portfolio

mece:
  domain: https://ohtu-testi.it.helsinki.fi

environment: dev

adminAccounts: opettaja@helsinki.fi, opiskelija@helsinki.fi

feed.client.implementation: mock

embedlyApiKey: dd741e653b0e4841bc59a60650031057
