server:
    port: 8080
    session-timeout: 1800 # Seconds

spring:
    profiles:
        active: qa
    datasource:
        dataSourceClassName: ${datasource.dataSourceClassName}
        url: ${datasource.url}
        databaseName: ${datasource.databaseName}
        serverName: ${datasource.serverName}
        username: ${datasource.username}
        password: ${datasource.password}

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        database: ${jpa.database}
        openInView: ${jpa.openInView}
        show_sql: ${jpa.show_sql}
        generate-ddl: ${jpa.generate-ddl}
        hibernate:
            ddl-auto: ${jpa.hibernate.ddl-auto}
            naming-strategy: ${jpa.hibernate.naming-strategy}
        properties:
            hibernate.cache.use_second_level_cache: ${jpa.properties.hibernate.cache.use_second_level_cache}
            hibernate.cache.use_query_cache: ${jpa.properties.hibernate.cache.use_query_cache}
            hibernate.generate_statistics: ${jpa.properties.hibernate.generate_statistics}
            hibernate.cache.region.factory_class: ${jpa.properties.hibernate.cache.region.factory_class}

metrics:
    jmx.enabled: true

oodi:
    base.url: https://oprek2.it.helsinki.fi:30039
    client.implementation: rest

coursePage:
    base.url: https://dev.courses.helsinki.fi/api/v1
    client.implementation: rest
    defaultCourseImageUri: /assets/images/course/default_course_image.jpg

unisport:
    client.implementation: rest
    base.url: https://unisport.fi

googleAnalyticsAccount: UA-55852460-2

hostUrl: https://qa.student.helsinki.fi
loginUrlTeacher: /saml/login/alias/teacher
loginUrlStudent: /saml/login/alias/student
logoutUrl: /saml/logout?local=true
teacherAppUrl: https://qa.teacher.helsinki.fi
studentAppUrl: https://qa.student.helsinki.fi
portfolioUrl:
  student: https://qa.student.helsinki.fi/portfolio
  teacher: https://qa.teacher.helsinki.fi/portfolio

embedlyApiKey: 69bd6bec8cb649df9b7ae0bdc972b206

environment: qa