server:
    port: 8080
    session.timeout: 1800 # Seconds

spring:
    profiles:
        active: prod
    datasource:
        dataSourceClassName: ${datasource.dataSourceClassName}
        url: ${datasource.url}
        databaseName: ${datasource.databaseName}
        serverName: ${datasource.serverName}
        username: ${datasource.username}
        password: ${datasource.password}

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        database: ${jpa.database}
        openInView: ${jpa.openInView}
        show_sql: ${jpa.show_sql}
        generate-ddl: ${jpa.generate-ddl}
        hibernate:
            ddl-auto: ${jpa.hibernate.ddl-auto}
            naming-strategy: ${jpa.hibernate.naming-strategy}
        properties:
            hibernate.cache.use_second_level_cache: ${jpa.properties.hibernate.cache.use_second_level_cache}
            hibernate.cache.use_query_cache: ${jpa.properties.hibernate.cache.use_query_cache}
            hibernate.generate_statistics: ${jpa.properties.hibernate.generate_statistics}
            hibernate.cache.region.factory_class: ${jpa.properties.hibernate.cache.region.factory_class}

logging:
    level:
        org.springframework.security.saml: ERROR
        org.opensaml: FATAL

metrics:
    jmx.enabled: true

oodi:
    base.url: https://esbmt1.it.helsinki.fi:443/doo-oodi/v1/productiondb
    client.implementation: rest

coursePage:
    base.url: https://courses.helsinki.fi/api/v1
    client.implementation: rest
    defaultCourseImageUri: /assets/images/course/default_course_image.jpg
    checkUpdates.interval.seconds: 60

optime:
    base.url: https://esbmt1.it.helsinki.fi
    client.implementation: rest

unisport:
    client.implementation: rest
    base.url: https://unisport.fi
    userAuthorizationUrl: https://unisport.fi/ext/opintoni/authorization

recommendations:
    maxRecommendations: 20
    uidPrefix: opintohistoria_

googleAnalyticsAccount:
    main: UA-55852460-5
    student: UA-6314483-6
    teacher: UA-6314483-7

hostUrl: https://student.helsinki.fi
loginUrlTeacher: /saml/login/alias/teacher
loginUrlStudent: /saml/login/alias/student
logoutUrl: /saml/logout?local=true
teacherAppUrl: https://teacher.helsinki.fi
studentAppUrl: https://student.helsinki.fi
portfolioUrl:
  student: https://student.helsinki.fi/portfolio
  teacher: https://teacher.helsinki.fi/portfolio

mece:
  domain: https://mece.it.helsinki.fi

embedlyApiKey: 2cb3558d787c40a9a7c334bc276297a6

environment: prod
