server:
    port: 8080
    servlet:
        session:
            cookie:
                http-only: true
                domain: helsinki.fi
                path: /
                max-age: 86400s
                name: OO_LOCAL_SESSION_ID
            timeout: 3600s

# Needed as integer for mece configuration
session.timeout: 3600

spring:
    profiles:
        active: local-dev
    datasource:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        url: jdbc:postgresql://my-studies-psql:5433/opintoni
        databaseName: opintoni
        serverName: my-studies-psql
        username: opintoni
        password: opintoni
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        database: PostgreSQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            cache_region_factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
    mail:
        host: localhost
        port: 2525
    main:
        allow-bean-definition-overriding: true
    servlet:
        multipart:
            max-file-size: 16MB
            max-request-size: 18MB

environment: local

metrics:
    jmx.enabled: false

# Disable the spring security default configuration from spring-boot-actuator
management:
    endpoints:
        enabled-by-default: false
        web:
            base-path: /
            path-mapping:
                health: health
                info: /api/public/v1/version-info
    endpoint:
        health:
            enabled: true
        info:
            enabled: true

redis:
    host: localhost
    port: 6380
    defaultCacheExpirationSeconds: 31536000 #One year

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

feedback:
    recipient:
        student: studentfeedback@localhost
        teacher: teacherfeedback@localhost
        profile: profilefeedback@localhost
        academicProfile: academicprofilefeedback@localhost
    anonymous:
        fromAddress: doo-projekti@helsinki.fi
        replyToAddress: noreply@helsinki.fi

hibernate:
    connection:
        handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION

userDefaults:
    defaultFavorites:
        - type: UNICAFE
          restaurantId : 39
        - type: TWITTER
          value: helsinkiuni
        - type: RSS
          url: https://www.helsinki.fi/fi/feeds/news/rss
        - type: RSS
          url: https://helsinginyliopisto.etapahtuma.fi/Default.aspx?tabid=959&format=atom
        - type: FLAMMA_NEWS
        - type: FLAMMA_EVENTS
    defaultUsefulLinks :
        studentDefaultUsefulLinks :
            - url: http://helsinki.fi/office365
              description: usefulLinks.email
              orderIndex: 0
            - url: https://helsinkifi-my.sharepoint.com/
              description: usefulLinks.oneDrive
              orderIndex: 1
        teacherDefaultUsefulLinks :
            - url: http://tuhat.helsinki.fi/
              description: usefulLinks.tuhat
              orderIndex: 8
            - url: https://www.researchgate.net/
              description: usefulLinks.researchGate
              orderIndex: 9
            - url: http://www.helsinki.fi/optime
              description: usefulLinks.optimePortal
              orderIndex: 10
            - url: https://helsinkifi-my.sharepoint.com/
              description: usefulLinks.oneDrive
              orderIndex: 11
        studentOpenUniversityDefaultUsefulLinks:
            - url:
                fi: https://www.helsinki.fi/fi/avoin-yliopisto
                sv: https://www.helsinki.fi/sv/oppna-universitetet
                en: https://www.helsinki.fi/en/open-university
              description: usefulLinks.openUniversity
              orderIndex: 0
            - url: https://www.avoin.helsinki.fi/omat/osallistumiset/
              description: usefulLinks.openUniversityMyPages
              orderIndex: 1
        teacherOpenUniversityDefaultUsefulLinks:
            - url: http://www.helsinki.fi/optime
              description: usefulLinks.optimePortal
              orderIndex: 4
    defaultFacultyCode: default
    facultyUsefulLinks:
        teacherFacultyLinks:
            - faculty: A93000
              url: https://www.avoin.helsinki.fi/omat/osallistumiset/
              description: usefulLinks.openUniversity
              orderIndex: 1

courses:
    examTypeCodes: 8,16,19,20,23,27,28

avatarSize: 510

saml:
  idp.metadataUrl: https://login.helsinki.fi/metadata/sign-hy-metadata.xml
  teacher:
    alias: teacher
  student:
    alias: student

appRelativeUrl:
hostUrl: http://local.student.helsinki.fi:3000
loginUrlTeacher: http://local.teacher.helsinki.fi:3000/info/local-login
loginUrlStudent: http://local.student.helsinki.fi:3000/info/local-login
logoutUrl: /logout
teacherAppUrl: http://local.teacher.helsinki.fi:3000
studentAppUrl: http://local.student.helsinki.fi:3000
profileUrl:
    student: http://local.student.helsinki.fi:3000/profile
    teacher: http://local.teacher.helsinki.fi:3000/profile

adminAccounts: opettaja@helsinki.fi, opiskelija@helsinki.fi

embedlyApiKey: dd741e653b0e4841bc59a60650031057

esb:
    base.url: https://esbmt2.it.helsinki.fi/devel
    client.implementation: mock

googleAnalyticsAccount:
    main: UA-55852460-3
    profile: UA-55852460-18
    student: UA-55852460-9
    teacher: UA-55852460-9

guide:
    base.url: https://dev.guide.student.helsinki.fi/api/v1
    client.implementation: mock

mece:
    domain: https://mece.ohtu-test.it.helsinki.fi

meceSecretKey: W778UXMJ7PFQTKG2RM8NR2H7T3QE5ZTL

newsfeeds:
    maxItems:
        student: 6
        teacher: 4
    client.implementation: mock
    studentFeedCategory: oppilas
    studentFeedsByLocale:
        fi: https://flamma.helsinki.fi/infotaulu/atom-tiedotteet-opiskelijalle.xml
        sv: https://flamma.helsinki.fi/infotaulu/atom-tiedotteet-opiskelijalle-sv.xml
        en: https://flamma.helsinki.fi/infotaulu/atom-tiedotteet-opiskelijalle-en.xml
    teacherFeedsByLocale:
        fi: https://flamma.helsinki.fi/infotaulu/atom-tiedotteet-opetusasiat.xml
        sv: https://flamma.helsinki.fi/infotaulu/atom-tiedotteet-opetusasiat-sv.xml
        en: https://flamma.helsinki.fi/infotaulu/atom-tiedotteet-opetusasiat-en.xml
    guideFeedsByLocale:
        fi: https://guide.student.helsinki.fi/fi/news/feed.xml
        sv: https://guide.student.helsinki.fi/sv/news/feed.xml
        en: https://guide.student.helsinki.fi/en/news/feed.xml

optime:
    client.implementation: mock
    useOptimeFeedForWebCalendar: false

publicWww:
    base.url: https://www.helsinki.fi
    path: fi/feeds/filtered-news/rss/11405/all

search:
  maxSearchResults: 100
  maxCategoryResults: 10

recommendations:
  maxRecommendations: 20
  uidPrefix: opintohistoriatesti_

iam:
    base.url: https://esb-api.it.helsinki.fi:443/iam/
    client.implementation: mock
    useHttpClientCertificate: false

httpClient:
  readTimeout: 40000
  connectTimeout: 3000
  maxTotal: 700
  defaultMaxPerRoute: 500

cache:
    timeToLiveSeconds: 3600
    studentEvents:
        timeToLiveSeconds: 600
        maxEntriesLocalHeap: 600
    studentEnrollments:
        timeToLiveSeconds: 600
        maxEntriesLocalHeap: 500
    teacherEvents:
        timeToLiveSeconds: 3600
        maxEntriesLocalHeap: 500
    teacherCourses:
        timeToLiveSeconds: 3600
        maxEntriesLocalHeap: 500
    courseUnitRealisationTeachers:
        timeToLiveSeconds: 28800
        maxEntriesLocalHeap: 10000
    studentNews:
        timeToLiveSeconds: 3600
        maxEntriesLocalHeap: 1
    teacherNews:
        timeToLiveSeconds: 3600
        maxEntriesLocalHeap: 1
    isOpenUniversityStudent:
        timeToLiveSeconds: 86400
        maxEntriesLocalHeap: 10000
    isOpenUniversityTeacher:
        timeToLiveSeconds: 86400
        maxEntriesLocalHeap: 5000
    europeHelsinkiTimeZone:
        timeToLiveSeconds: 3600
        maxEntriesLocalHeap: 1
    feeds:
        timeToLiveSeconds: 3600
        maxEntriesLocalHeap: 200
    studyRights:
        timeToLiveSeconds: 3600
        maxEntriesLocalHeap: 500
    studyAttainments:
        timeToLiveSeconds: 3600
        maxEntriesLocalHeap: 500
    courseCms:
        timeToLiveSeconds: 3600
        maxEntriesLocalHeap: 500

staticResourceCachingPeriod: 31536000

coursePage:
    base.url: https://dev.courses.helsinki.fi
    api.path: /api/v1
    client.implementation: mock
    defaultCourseImageUri: /assets/images/course/default_course_image.jpg

courseCms:
    base.url: https://master.uh-courses.silta.wdr.io
    client.implementation: mock
    enabled: true
    useAfterDate: 2020-07-27

studies.base.url: https://studies-qa.it.helsinki.fi

sotka:
    base.url: https://esbmt2.it.helsinki.fi/sotkuqa
    client.implementation: mock

fileStorage:
  path: /opt/opintoni/files
  uri: /files

faculty:
  A93000:
  H57:
  H90:
  H55:
  H40:
  H60:
  H30:
  H80:
  H50:
  H20:
  H74:
  H10:
  H70:
  A57000:
  A90000:
  A55000:
  A40000:
  A60000:
  A30000:
  A80000:
  A50000:
  A20000:
  A74000:
  A10000:
  A70000:

feed.client.implementation: mock

language:
    available: fi,sv,en
    default: fi

pilotDegreeProgrammes:
    - KH40_001
    - KH50_002
    - KH50_006
    - KH40_006
    - KH50_003
    - KH40_003
    - KH40_004
    - KH40_005
    - KH50_007
    - KH50_004
    - KH50_001
    - KH40_002
    - KH10_001
    - KH50_005
    - MH50_004
    - MH40_012
    - MH50_010
    - MH40_005
    - MH50_002
    - MH40_003
    - MH50_011
    - MH40_015
    - MH50_006
    - MH50_013
    - MH50_007
    - MH40_002
    - MH40_009
    - MH40_013
    - MH40_010
    - MH40_006
    - MH50_012
    - MH50_001
    - MH50_008
    - MH50_005
    - MH40_008
    - MH40_014
    - MH40_007
    - MH40_001
    - MH10_001
    - MH50_003
    - MH50_009
    - KH20_001
    - KH30_001
    - KH30_002
    - KH55_001
    - KH57_001
    - KH57_002
    - KH57_003
    - KH60_001
    - KH70_001
    - KH70_002
    - KH70_003
    - KH70_004
    - KH74_001
    - KH80_001
    - KH80_002
    - KH80_003
    - KH80_004
    - KH90_001
    - MH20_001
    - MH20_002
    - MH30_001
    - MH30_002
    - MH30_003
    - MH30_004
    - MH30_005
    - MH40_004
    - MH40_011
    - MH55_001
    - MH57_001
    - MH57_002
    - MH57_003
    - MH57_004
    - MH57_005
    - MH60_001
    - MH70_001
    - MH70_002
    - MH70_003
    - MH70_004
    - MH70_005
    - MH70_006
    - MH70_007
    - MH70_008
    - MH70_009
    - MH80_001
    - MH80_002
    - MH80_003
    - MH80_004
    - MH80_005
    - MH80_006
    - MH80_007
    - MH90_001

fileService:
    client:
        implementation: mock
        storage: memory

inactiveUserCleaner:
    cron: "0 0 * * * *"
    testUserToInactivate: "mag_simp"

oodi:
    base.url: https://esbmt2.it.helsinki.fi:4443/doo-oodi/dev/testdb
    client.implementation: mock
    useHttpClientCertificate: false

obar:
    baseUrl: #http://localhost:8090
    privateKey: |
        -----BEGIN RSA PRIVATE KEY-----
        MIICXQIBAAKBgQDjOuYIREZqcc1wGBtu1emTbt7ryggKV2tbhRqn3nr+OPYfuBbN
        2ifc6JFng5bfJjNGDEjN8mSHrZxgD7aGBOd4q0U2yRGNJQkQ2tWUqF1ABsYEpyWp
        1eubSvViHwd3rmEqcAyok4ImdqRtKTVgPVGXsd8qTmix8+RCGQhCFVK1vwIDAQAB
        AoGAQkr8sYy5vnRVK07dMgjWjFzcTI40qk+20oySqkcOOv0DUV2zyXrMBncTdM+/
        RHswmk8bLnp5Odw8swnihlcH8G/K2KQO080mMcl7eH7BTNWg4+ueCrJOWojGvUmG
        gawU6yswv4V7OJiuMrtmxfvXtosKRjiuQw//h53Q3N3naAECQQDzM9efxEDrdGlf
        LP3MeC3+uRFHilT0JoVbY5v6HBhiWuLJ8XEGg1XP3B8H/n4pSY4sAVQKZ+lIhCY6
        B87a3DZBAkEA7y/ko4ZkDtDdr8COXgNV2Spi0VWfpGFMd8zRtXich+tnkSq2SgNW
        6z5ntVTbMCA2eTdd1MKASMv6DxbNAWvr/wJBAK5Yre1k/b1NuPR4BoH8bcy7031b
        18cnjlaTtA+68GgiC48FvScUJAJdJQnQEZV7m6ZEVYEYOQ65XcYgLtSLJYECQQDe
        4lQ+hWcL31oVAmwn8xe2bCb1RsKinQByymvInQHQLm6t+Y0wXvhJ8jcV5GLz77CT
        OCK5th1wuJLmKKsUXgrlAkAEbzqZICKYFzA3b4p+xKsgyQ7TYPXJq60gvINsbWql
        hVgbKTsLYrW38ov5Qh1vEO84nxnNdyUQrHizVUFP1Lg2
        -----END RSA PRIVATE KEY-----
    jwtTimeout: 60 # seconds

studyregistry:
    oodiDatasets:
        - STUDENT_ENROLLMENTS
        - STUDENT_EVENTS
        - TEACHER_COURSES
        - TEACHER_EVENTS
        - STUDY_ATTAINMENTS
        - STUDY_RIGHTS
        - COURSE_REALISATION_TEACHERS
        - PERSON_INFO
sisu:
    baseUrl: https://esbmt2.it.helsinki.fi:443/secure/doo-sisu
    client.implementation: mock
    apiPath: /graphql
