saml:
  idp.metadataUrl: https://login-test.it.helsinki.fi/metadata/sign-hy-test-metadata.xml

loginUrlTeacher: /saml/login/alias/teacher
loginUrlStudent: /saml/login/alias/student
logoutUrl: /saml/logout
