server:
    port: 8080
    servlet:
        session:
            cookie:
                http-only: true
                domain: helsinki.fi
                path: /
                max-age: 86400s
            timeout: 3600s

# Needed as integer for mece configuration
session.timeout: 3600

spring:
    main:
        allow-bean-definition-overriding: true
    servlet:
        multipart:
            max-file-size: 16MB
            max-request-size: 18MB

# Disable the spring security default configuration from spring-boot-actuator
management:
    endpoints:
        enabled-by-default: false
        web:
            base-path: /
            path-mapping:
                health: health
                info: /api/public/v1/version-info
    endpoint:
        health:
            enabled: true
        info:
            enabled: true

redis:
    host: localhost
    port: 6379
    defaultCacheExpirationSeconds: 31536000 #One year

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

feedback:
    recipient:
        student: neu-tuki@helsinki.fi
        teacher: opetusteknologia@helsinki.fi
        profile: opetusteknologia@helsinki.fi
        academicProfile: opetusteknologia@helsinki.fi

    anonymous:
        fromAddress: doo-projekti@helsinki.fi
        replyToAddress: noreply@helsinki.fi

hibernate:
    connection:
        handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION

userDefaults :
    defaultFavorites:
        - type: UNICAFE
          restaurantId : 39
        - type: TWITTER
          value: helsinkiuni
        - type: RSS
          url: https://www.helsinki.fi/fi/feeds/news/rss
        - type: RSS
          url: http://helsinginyliopisto.etapahtuma.fi/Default.aspx?tabid=959&format=atom
        - type: FLAMMA_NEWS
        - type: FLAMMA_EVENTS
    defaultUsefulLinks :
        studentDefaultUsefulLinks :
            - url: http://helsinki.fi/office365
              description: usefulLinks.email
              orderIndex: 0
            - url: https://helsinkifi-my.sharepoint.com/
              description: usefulLinks.oneDrive
              orderIndex: 1
        teacherDefaultUsefulLinks :
            - url: http://tuhat.helsinki.fi/
              description: usefulLinks.tuhat
              orderIndex: 8
            - url: https://www.researchgate.net/
              description: usefulLinks.researchGate
              orderIndex: 9
            - url: http://www.helsinki.fi/optime
              description: usefulLinks.optimePortal
              orderIndex: 10
            - url: https://helsinkifi-my.sharepoint.com/
              description: usefulLinks.oneDrive
              orderIndex: 11
        studentOpenUniversityDefaultUsefulLinks:
            - url:
                fi: https://www.helsinki.fi/fi/avoin-yliopisto
                sv: https://www.helsinki.fi/sv/oppna-universitetet
                en: https://www.helsinki.fi/en/open-university
              description: usefulLinks.openUniversity
              orderIndex: 0
            - url: https://www.avoin.helsinki.fi/omat/osallistumiset/
              description: usefulLinks.openUniversityMyPages
              orderIndex: 1
        teacherOpenUniversityDefaultUsefulLinks:
            - url: http://www.helsinki.fi/optime
              description: usefulLinks.optimePortal
              orderIndex: 4
    defaultFacultyCode: default
    facultyUsefulLinks:
        teacherFacultyLinks:
            - faculty: A93000
              url: https://www.avoin.helsinki.fi/omat/osallistumiset/
              description: usefulLinks.openUniversity
              orderIndex: 1

courses:
    examTypeCodes: 8,16,19,20,23,27,28

avatarSize: 510

saml:
  idp.metadataUrl: https://login.helsinki.fi/metadata/sign-hy-metadata.xml
  teacher:
    alias: teacher
  student:
    alias: student

studentAppUrl:
teacherAppUrl:
appRelativeUrl:


newsfeeds:
    maxItems:
        student: 6
        teacher: 4
    client.implementation: rest
    studentFeedCategory: oppilas
    studentFeedsByLocale:
        fi: https://flamma.helsinki.fi/infotaulu/atom-tiedotteet-opiskelijalle.xml
        sv: https://flamma.helsinki.fi/infotaulu/atom-tiedotteet-opiskelijalle-sv.xml
        en: https://flamma.helsinki.fi/infotaulu/atom-tiedotteet-opiskelijalle-en.xml
    teacherFeedsByLocale:
        fi: https://flamma.helsinki.fi/infotaulu/atom-tiedotteet-opetusasiat.xml
        sv: https://flamma.helsinki.fi/infotaulu/atom-tiedotteet-opetusasiat-sv.xml
        en: https://flamma.helsinki.fi/infotaulu/atom-tiedotteet-opetusasiat-en.xml
    guideFeedsByLocale:
        fi: https://guide.student.helsinki.fi/fi/news/feed.xml
        sv: https://guide.student.helsinki.fi/sv/news/feed.xml
        en: https://guide.student.helsinki.fi/en/news/feed.xml

publicWww:
    base.url: https://www.helsinki.fi
    path: fi/feeds/filtered-news/rss/11405/all

unisport:
    base.url: https://beta.unisport.fi
    tokenValidForSeconds: 10
    jwt.service.implementation: expiring

search:
  maxSearchResults: 100
  maxCategoryResults: 10

recommendations:
  maxRecommendations: 20
  uidPrefix: opintohistoriatesti_

iam:
    base.url: https://esb-api.it.helsinki.fi:443/iam/

httpClient:
  readTimeout: 40000
  connectTimeout: 3000
  maxTotal: 700
  defaultMaxPerRoute: 500

cache:
    timeToLiveSeconds: 3600
    studentEvents:
        timeToLiveSeconds: 3600
        maxEntriesLocalHeap: 600
    studentEnrollments:
        timeToLiveSeconds: 1800
        maxEntriesLocalHeap: 500
    teacherEvents:
        timeToLiveSeconds: 3600
        maxEntriesLocalHeap: 500
    teacherCourses:
        timeToLiveSeconds: 3600
        maxEntriesLocalHeap: 500
    courseUnitRealisationTeachers:
        timeToLiveSeconds: 28800
        maxEntriesLocalHeap: 10000
    studentNews:
        timeToLiveSeconds: 3600
        maxEntriesLocalHeap: 1
    teacherNews:
        timeToLiveSeconds: 3600
        maxEntriesLocalHeap: 1
    isOpenUniversityStudent:
        timeToLiveSeconds: 86400
        maxEntriesLocalHeap: 10000
    isOpenUniversityTeacher:
        timeToLiveSeconds: 86400
        maxEntriesLocalHeap: 5000
    europeHelsinkiTimeZone:
        timeToLiveSeconds: 3600
        maxEntriesLocalHeap: 1
    feeds:
        timeToLiveSeconds: 3600
        maxEntriesLocalHeap: 200

staticResourceCachingPeriod: 31536000

fileStorage:
  path: /opt/opintoni/files
  uri: /files

faculty:
  A93000:
  H57:
  H90:
  H55:
  H40:
  H60:
  H30:
  H80:
  H50:
  H20:
  H74:
  H10:
  H70:
  A57000:
  A90000:
  A55000:
  A40000:
  A60000:
  A30000:
  A80000:
  A50000:
  A20000:
  A74000:
  A10000:
  A70000:

feed.client.implementation: remote

language:
    available: fi,sv,en
    default: fi

pilotDegreeProgrammes:
    - KH40_001
    - KH50_002
    - KH50_006
    - KH40_006
    - KH50_003
    - KH40_003
    - KH40_004
    - KH40_005
    - KH50_007
    - KH50_004
    - KH50_001
    - KH40_002
    - KH10_001
    - KH50_005
    - MH50_004
    - MH40_012
    - MH50_010
    - MH40_005
    - MH50_002
    - MH40_003
    - MH50_011
    - MH40_015
    - MH50_006
    - MH50_013
    - MH50_007
    - MH40_002
    - MH40_009
    - MH40_013
    - MH40_010
    - MH40_006
    - MH50_012
    - MH50_001
    - MH50_008
    - MH50_005
    - MH40_008
    - MH40_014
    - MH40_007
    - MH40_001
    - MH10_001
    - MH50_003
    - MH50_009
    - KH20_001
    - KH30_001
    - KH30_002
    - KH55_001
    - KH57_001
    - KH57_002
    - KH57_003
    - KH60_001
    - KH70_001
    - KH70_002
    - KH70_003
    - KH70_004
    - KH74_001
    - KH80_001
    - KH80_002
    - KH80_003
    - KH80_004
    - KH90_001
    - MH20_001
    - MH20_002
    - MH30_001
    - MH30_002
    - MH30_003
    - MH30_004
    - MH30_005
    - MH40_004
    - MH40_011
    - MH55_001
    - MH57_001
    - MH57_002
    - MH57_003
    - MH57_004
    - MH57_005
    - MH60_001
    - MH70_001
    - MH70_002
    - MH70_003
    - MH70_004
    - MH70_005
    - MH70_006
    - MH70_007
    - MH70_008
    - MH70_009
    - MH80_001
    - MH80_002
    - MH80_003
    - MH80_004
    - MH80_005
    - MH80_006
    - MH80_007
    - MH90_001

fileService:
    client:
        implementation: mock
        storage: fileSystem
        path: /opt/opintoni/files/profile

inactiveUserCleaner:
    cron: "0 0 5 * * *"

obar:
    jwtTimeout: 60 # seconds

studyregistry:
    oodiDatasets:
        - STUDENT_ENROLLMENTS
        - STUDENT_EVENTS
        - TEACHER_COURSES
        - TEACHER_EVENTS
        - STUDY_ATTAINMENTS
        - STUDY_RIGHTS
        - COURSE_REALISATION_TEACHERS
        - PERSON_INFO
sisu:
    baseUrl: https://esbmt2.it.helsinki.fi:443/secure/doo-sisu
    client.implementation: graphQL
    apiPath: /graphql
