server:
    servlet:
        session:
            cookie:
                secure: true
                name: OO_QA_SESSION_ID

spring:
    profiles:
        active: qa
    datasource:
        dataSourceClassName: ${datasource.dataSourceClassName}
        url: ${datasource.url}
        databaseName: ${datasource.databaseName}
        serverName: ${datasource.serverName}
        username: ${datasource.username}
        password: ${datasource.password}

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        database: ${jpa.database}
        openInView: ${jpa.openInView}
        show_sql: ${jpa.show_sql}
        generate-ddl: ${jpa.generate-ddl}
        hibernate:
            ddl-auto: ${jpa.hibernate.ddl-auto}
            naming-strategy: ${jpa.hibernate.naming-strategy}
        properties:
            hibernate.cache.use_second_level_cache: ${jpa.properties.hibernate.cache.use_second_level_cache}
            hibernate.cache.use_query_cache: ${jpa.properties.hibernate.cache.use_query_cache}
            hibernate.generate_statistics: ${jpa.properties.hibernate.generate_statistics}
            hibernate.cache.region.factory_class: ${jpa.properties.hibernate.cache.region.factory_class}
    mail:
        host: smtp.helsinki.fi
        port: 25

logging:
    level:
        org.springframework.security.saml: ERROR
        org.opensaml: FATAL

metrics:
    jmx.enabled: true

oodi:
    base.url: https://esbmt2.it.helsinki.fi:443/secure/doo-oodi/dev/testdb
    client.implementation: rest
    useHttpClientCertificate: true

coursePage:
    base.url: https://dev.courses.helsinki.fi
    api.path: /api/v1
    client.implementation: rest
    defaultCourseImageUri: /assets/images/course/default_course_image.jpg
    checkUpdates.interval.seconds: 60

guide:
    base.url: https://dev.guide.student.helsinki.fi/api/v1
    client.implementation: rest

newsfeeds:
    studentFeedsByLocale:
        fi: https://flamma.helsinki.fi/infotaulu/atom-bulletin.xml
        sv: https://flamma.helsinki.fi/infotaulu/atom-bulletin-sv.xml
        en: https://flamma.helsinki.fi/infotaulu/atom-bulletin-en.xml
    teacherFeedsByLocale:
        fi: https://flamma.helsinki.fi/infotaulu/atom-tiedotteet-opetusasiat.xml
        sv: https://flamma.helsinki.fi/infotaulu/atom-tiedotteet-opetusasiat-sv.xml
        en: https://flamma.helsinki.fi/infotaulu/atom-tiedotteet-opetusasiat-en.xml
    guideFeedsByLocale:
        fi: https://dev.guide.student.helsinki.fi/fi/news/feed.xml
        sv: https://dev.guide.student.helsinki.fi/sv/news/feed.xml
        en: https://dev.guide.student.helsinki.fi/en/news/feed.xml

saml:
  idp.metadataUrl: https://login-test.it.helsinki.fi/metadata/sign-hy-test-metadata.xml
  teacher:
    alias: teacher
  student:
    alias: student

esb:
    base.url: https://esbmt2.it.helsinki.fi/devel
    client.implementation: rest

iam:
    client.implementation: mock

unisport:
    client.implementation: rest
    userAuthorizationUrl: https://unisport.fi/ext/opintoni/authorization

recommendations:
    maxRecommendations: 20
    uidPrefix: opintohistoria_

googleAnalyticsAccount:
    main: UA-55852460-2
    profile: UA-55852460-16
    student: UA-55852460-9
    teacher: UA-55852460-9

hostUrl: https://qa.student.helsinki.fi
loginUrlTeacher: /saml/login/alias/teacher
loginUrlStudent: /saml/login/alias/student
logoutUrl: /saml/logout?local=true
teacherAppUrl: https://qa.teacher.helsinki.fi
studentAppUrl: https://qa.student.helsinki.fi
profileUrl:
  student: https://qa.student.helsinki.fi/profile
  teacher: https://qa.teacher.helsinki.fi/profile

mece:
  domain: https://mece.ohtu-test.it.helsinki.fi

embedlyApiKey: 69bd6bec8cb649df9b7ae0bdc972b206

environment: qa

inactiveUserCleaner:
    cron: "0 0 * * * *"
    testUserToInactivate: "doo_2"
