version: '3.5'

services:
  my-studies-redis:
    container_name: my-studies-redis
    image: redis:3.2-alpine
    command: redis-server
    ports:
      - 6379:6379
  my-studies-psql:
    container_name: my-studies-psql
    image: postgres:9.4-alpine
    environment:
      - POSTGRES_USER=opintoni
      - POSTGRES_PASSWORD=opintoni
      - POSTGRES_DB=opintoni
    volumes:
      - ../docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432