version: '3.5'

services:
  my-studies-redis:
    image: redis:3.2-alpine
    command: redis-server
  my-studies-psql:
    image: postgres:9.4-alpine
    environment:
      - POSTGRES_USER=opintoni
      - POSTGRES_PASSWORD=opintoni
      - POSTGRES_DB=opintoni
    volumes:
      - ../docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  gradle:
      build: ./gradle
      working_dir: /opt/mystudies/app
      volumes:
        - ~/.gradle:/root/.gradle
        - ~/.m2:/root/.m2
        - ../../:/opt/mystudies
      depends_on:
        - my-studies-redis
        - my-studies-psql