version: '3.5'

services:
  my-studies-redis:
    image: redis:3.2-alpine
    command: redis-server
  my-studies-psql:
    image: postgres:9.4-alpine
    environment:
      - POSTGRES_USER=opintoni
      - POSTGRES_PASSWORD=opintoni
    volumes:
      - ../docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    tmpfs:
      - /var/lib/postgresql/data:rw
  my-studies-builder:
    build:
      context: ./builder
    image: my-studies-builder:latest
    volumes:
      - ../../:/opt/mystudies
    depends_on:
      - my-studies-redis
      - my-studies-psql
